name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    #  needs: execute-release
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 

       - name: Set Branch Name
         id: branch_name
         run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

       - name: Set Latest Tag
         id: set_latest_tag
         run: |
           LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")
           echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
           echo "Latest tag is ${{ env.LATEST_TAG }}"

       - name: Authenticate to Azure
         uses: azure/login@v2
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
       - name: Build and push image
         uses: azure/docker-login@v1
         with:
              login-server: pohlmanproteancontainerregistry.azurecr.io
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}
       - run: |
            docker build -t pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image -f Dockerfile .
            docker push pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image

       - name: Deploy to Azure Container Instances
         run: |
              az container create \
                --resource-group pohlmanprotean \
                --name ${{ env.BRANCH_NAME }}-az-api-pohlmanprotean \
                --image pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image:${{ github.sha }} \
                --os-type Linux \
                --cpu 1 \
                --memory 1 \
                --registry-login-server pohlmanproteancontainerregistry.azurecr.io \
                --registry-username ${{ secrets.ACR_USERNAME }} \
                --registry-password ${{ secrets.ACR_PASSWORD }} \
                --dns-name-label pohlmanprotea${{ github.run_number }} \