name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    #  needs: execute-release
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 

       - name: Set Branch Name
         id: branch_name
         run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

       - name: Set Latest Tag
         id: set_latest_tag
         run: |
           LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")
           echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
           echo "Latest tag is ${{ env.LATEST_TAG }}"

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.7.1

       - name: Authenticate to Azure
         uses: azure/login@v2
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

       - name: Register Microsoft.ContainerInstance provider
         run: |
          az provider register --namespace Microsoft.ContainerInstance
      
       - name: Login to Azure Container Registry
         run: |
            az acr login --name pohlmanproteancontainerregistry
            az container create --resource-group pohlmanprotean --name ${{ env.BRANCH_NAME }}-az-api-pohlmanprotean --os-type Linux
  
       - name: Build Docker image
         run: |
            docker build -t pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image:${{ env.LATEST_TAG }} -f Dockerfile .
       
       - name: Push Docker image to Azure Container Registry
         run: |
            docker push pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image:${{ env.LATEST_TAG }}
        
       - name: Replace dots in tag for Cloud Run
         run: echo "REVISION_TAG=$(echo ${{ env.LATEST_TAG }} | sed 's/\./-/g')" >> $GITHUB_ENV
        
       - name: Deploy to Azure Container Instances
         run: |
            az container create \
              --resource-group pohlmanprotean \
              --name ${{ env.BRANCH_NAME }}-az-api-pohlmanprotean \
              --image pohlmanproteancontainerregistry.azurecr.io/${{ env.BRANCH_NAME }}-az-api-pohlmanprotean-image:${{ env.LATEST_TAG }} \
              --cpu 1 \
              --memory 1 \
              --os-type Linux \
              --registry-login-server pohlmanproteancontainerregistry.azurecr.io \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --dns-name-label ${{ env.BRANCH_NAME }}-az-api-pohlmanprotean \
              --ports 8080